apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-flask-api

resources:
  - "../../base"

configMapGenerator:
- name: flask-api-config
  literals:
    - POSTGRES_HOST=postgres-db
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_DB=klyde_db
    - ENVIRONMENT=LOCAL-DEV