apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: flask-api
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000