apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-api

resources:
  - namespace.yaml
  - app-deployment.yaml
  - app-hpa.yaml
  - app-service.yaml
  - db-deployment.yaml
  - db-pv.yaml
  - db-secret.yaml
  - db-service.yaml