apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: flask-api
spec:
  template:
    spec:
      containers:
        - name: flask-api 
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"