apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: flask-api
spec:
  template:
    spec:
      containers:
        - name: postgres-db
          resources:
            limits:
              cpu: "1"
              memory: "2G"