name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deployment.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

permissions:
  id-token: write   # This is required for requesting the JWT     
  contents: read    # This is required for actions/checkout

env:
  TF_DIR: "./terraform"
  TF_VERSION: "1.6.3"
  AWS_REGION: eu-west-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::847399026905:role/gh-action-cloud-devops-mentorship-dev-role
  AWS_ROLE_SESSION_NAME: klyde_cloud_devops_mentorship

jobs:
  terraform:
    name: Terraform CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Initialization
      working-directory: ${{ env.TF_DIR }}
      run: |
        terraform init

    - name: Terraform Format Check
      working-directory: ${{ env.TF_DIR }}
      run: terraform fmt -check

    - name: Terraform Validation
      working-directory: ${{ env.TF_DIR }}
      run: terraform validate

    - name: Terratest
      working-directory: ${{ env.TF_DIR }}
      run: |
        # WIP

    - name: Terraform Apply or Destroy
      working-directory: ${{ env.TF_DIR }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi