name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - feature/* # for testing
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deployment.yml'
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

permissions:
  id-token: write   # This is required for requesting the JWT     
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: Terraform CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::847399026905:role/gh-action-flask-api-dev-role
        role-session-name: klyde_cloud_devops_mentorship

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.3

    - name: Terraform Initialization
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Format Check
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform Validation
      working-directory: ./terraform
      run: terraform validate

    - name: Terratest
      working-directory: ./terraform
      run: |
        # WIP

    - name: Terraform Apply or Destroy
      working-directory: ./terraform
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi